algoritmo "Calculadora de Delta"
var
     A,B,C,S:real
inicio
   ESCREVA ("Informe A:")
           leia(a)
   escreva ("Infrome B:")
           leia (b)
   escreva ("Informe C:")
           leia(c)
   S<- b^2-4*A*C
   escreva ("O resultado de Delta e ",S)
   se s>0 entao
   escreva(" Existem Duas raizes reais e diferentes")
   senao
   se s<0 entao
   escreva (" Nao existem raizes reais")
   senao
   se s=0 entao
   escreva (" Existe 1 raiz igual")
    fimse
    fimse
    fimse
fimalgoritmo